import { StyleSheet } from 'react-native';
import { webInputReset } from '../../../styles/webInput';

// Gemeinsame Styles der KundenDetail-Sektionen (unveraendert aus dem
// urspruenglichen KundenDetailScreen uebernommen).
export const styles = StyleSheet.create({
  root: { flex: 1, backgroundColor: '#EEF3FB' },
  content: { padding: 32 },
  backBtn: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 24 },
  backArrow: { fontSize: 22, color: '#4A8FE8', fontWeight: '600' },
  backLabel: { fontSize: 14, fontWeight: '600', color: '#4A8FE8' },
  pageHeader: { flexDirection: 'row', alignItems: 'center', gap: 16, marginBottom: 28 },
  avatar: { width: 56, height: 56, borderRadius: 28, alignItems: 'center', justifyContent: 'center' },
  avatarLetter: { fontSize: 22, fontWeight: '800' },
  customerName: { fontSize: 22, fontWeight: '800', color: '#152238' },
  customerSub: { fontSize: 14, color: '#4A6080', marginTop: 2 },
  card: {
    backgroundColor: '#fff', borderRadius: 14, padding: 20, marginBottom: 16,
    shadowColor: '#152238', shadowOpacity: 0.05, shadowOffset: { width: 0, height: 2 }, shadowRadius: 6, elevation: 2,
    borderWidth: 1, borderColor: 'rgba(21,34,56,0.08)',
  },
  cardTitle: { fontSize: 15, fontWeight: '700', color: '#152238', marginBottom: 14 },
  cardTitleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginBottom: 14 },
  infoRow: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#EEF3FB' },
  infoLabel: { fontSize: 13, color: '#4A6080' },
  infoValue: { fontSize: 13, fontWeight: '600', color: '#152238', textAlign: 'right', maxWidth: '60%' },
  editSection: { paddingTop: 4 },
  editBtns: { flexDirection: 'row', gap: 10, marginTop: 14 },
  editInput: {
    backgroundColor: '#F4F8FF', borderWidth: 1, borderColor: 'rgba(21,34,56,0.08)',
    borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: '#152238', marginBottom: 4, ...webInputReset,
  },
  editProfileBtn: { marginTop: 12, backgroundColor: 'rgba(74,143,232,0.08)', borderRadius: 8, paddingVertical: 9, paddingHorizontal: 16, alignSelf: 'flex-start', borderWidth: 1, borderColor: 'rgba(74,143,232,0.2)' },
  editProfileBtnText: { fontSize: 13, fontWeight: '700', color: '#4A8FE8' },
  cancelEditBtn: { borderRadius: 10, paddingVertical: 12, alignItems: 'center', backgroundColor: 'rgba(21,34,56,0.06)' },
  cancelEditText: { fontSize: 14, fontWeight: '600', color: '#4A6080' },
  typeRow: { flexDirection: 'row', gap: 10, marginBottom: 12 },
  typeChip: { flex: 1, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 6, paddingVertical: 10, borderRadius: 10, borderWidth: 2, borderColor: 'rgba(21,34,56,0.08)', backgroundColor: '#F4F8FF' },
  typeChipActive: { borderColor: '#4A8FE8', backgroundColor: 'rgba(74,143,232,0.08)' },
  typeChipText: { fontSize: 13, fontWeight: '700', color: '#4A6080' },
  typeChipTextActive: { color: '#4A8FE8' },
  levelRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 10, marginBottom: 10 },
  levelChip: { paddingHorizontal: 18, paddingVertical: 10, borderRadius: 10, borderWidth: 2 },
  levelChipText: { fontSize: 14, fontWeight: '700' },
  noLevel: { fontSize: 13, color: '#7A90AE', fontStyle: 'italic', marginTop: 4 },
  permRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#EEF3FB' },
  permLabel: { fontSize: 14, color: '#374151', fontWeight: '500' },
  sectionLabel: { fontSize: 13, fontWeight: '700', color: '#4A6080', textTransform: 'uppercase', letterSpacing: 0.5, marginTop: 16, marginBottom: 8 },
  exemptBox: { marginTop: 14, backgroundColor: '#FFFBEB', borderRadius: 10, borderWidth: 1, borderColor: '#FDE68A', padding: 14 },
  exemptRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', gap: 12 },
  exemptLabel: { flex: 1, fontSize: 14, color: '#92400E', fontWeight: '700' },
  exemptHint: { fontSize: 12, color: '#92400E', lineHeight: 17, marginTop: 8 },
  tokenDisplayRow: { flexDirection: 'row', gap: 10 },
  tokenDisplayItem: { flex: 1, backgroundColor: '#F4F8FF', borderRadius: 10, padding: 12, alignItems: 'center', borderWidth: 1, borderColor: 'rgba(21,34,56,0.08)' },
  tokenDisplayCount: { fontSize: 28, fontWeight: '800', color: '#152238' },
  tokenDisplayLabel: { fontSize: 11, fontWeight: '600', color: '#7A90AE', marginTop: 4, textAlign: 'center' },
  totalLine: { fontSize: 12, color: '#7A90AE', marginTop: 10 },
  totalLineCount: { fontSize: 13, fontWeight: '800', color: '#4A6080' },
  tokenResetBtn: { marginTop: 14, alignSelf: 'flex-start', backgroundColor: 'rgba(239,68,68,0.08)', borderRadius: 8, paddingVertical: 9, paddingHorizontal: 16, borderWidth: 1, borderColor: 'rgba(239,68,68,0.25)' },
  tokenResetBtnText: { fontSize: 13, fontWeight: '700', color: '#EF4444' },
  tokenResetBox: { marginTop: 14, backgroundColor: '#FEF2F2', borderWidth: 1.5, borderColor: '#FECACA', borderRadius: 12, padding: 16 },
  tokenResetTitle: { fontSize: 14, fontWeight: '800', color: '#991B1B', marginBottom: 6 },
  tokenResetSub: { fontSize: 13, color: '#7F1D1D', lineHeight: 19, marginBottom: 14 },
  tokenResetBtns: { flexDirection: 'row', gap: 10 },
  tokenResetYes: { flex: 1, backgroundColor: '#EF4444', borderRadius: 10, paddingVertical: 11, alignItems: 'center' },
  tokenResetYesText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  tokenResetNo: { flex: 1, backgroundColor: 'rgba(21,34,56,0.06)', borderRadius: 10, paddingVertical: 11, alignItems: 'center' },
  tokenResetNoText: { fontSize: 14, fontWeight: '600', color: '#4A6080' },
  grantBtn: { marginTop: 14, alignSelf: 'flex-start', backgroundColor: 'rgba(90,140,106,0.1)', borderRadius: 8, paddingVertical: 9, paddingHorizontal: 16, borderWidth: 1, borderColor: 'rgba(90,140,106,0.3)' },
  grantBtnText: { fontSize: 13, fontWeight: '700', color: '#5A8C6A' },
  grantTitle: { fontSize: 14, fontWeight: '800', color: '#152238', marginBottom: 4 },
  grantSub: { fontSize: 13, color: '#4A6080', lineHeight: 19, marginBottom: 12 },
  grantSuccessText: { fontSize: 13, fontWeight: '600', color: '#15803D', marginTop: 12 },
  activeRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', paddingVertical: 8, borderBottomWidth: 1, borderBottomColor: '#EEF3FB', marginBottom: 4 },
  activeRowLeft: { flexDirection: 'row', alignItems: 'center', gap: 8 },
  statusDot: { width: 9, height: 9, borderRadius: 5 },
  activeLabel: { fontSize: 13, fontWeight: '700', color: '#152238' },
  fieldLabel: { fontSize: 12, fontWeight: '700', color: '#4A6080', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 6, marginTop: 4 },
  formSection: { backgroundColor: '#F4F8FF', borderRadius: 10, padding: 16, marginBottom: 16 },
  input: { backgroundColor: '#fff', borderWidth: 1, borderColor: 'rgba(21,34,56,0.08)', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, fontSize: 14, color: '#152238', ...webInputReset },
  saveBtn: {
    backgroundColor: '#152238', borderRadius: 10, paddingVertical: 12, alignItems: 'center', marginTop: 16,
    shadowColor: '#152238', shadowOffset: { width: 0, height: 6 },
    shadowOpacity: 0.18, shadowRadius: 12, elevation: 6,
  },
  saveBtnText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  addBtn: { backgroundColor: 'rgba(74,143,232,0.08)', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 7, borderWidth: 1, borderColor: 'rgba(74,143,232,0.2)' },
  addBtnText: { fontSize: 13, fontWeight: '700', color: '#4A8FE8' },
  programRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  programChip: { paddingHorizontal: 12, paddingVertical: 7, borderRadius: 8, borderWidth: 1.5, borderColor: 'rgba(21,34,56,0.08)', backgroundColor: '#fff' },
  programChipActive: { borderColor: '#4A8FE8', backgroundColor: 'rgba(74,143,232,0.1)' },
  programChipText: { fontSize: 13, color: '#4A6080', fontWeight: '600' },
  programChipTextActive: { color: '#4A8FE8' },
  slotRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8, marginTop: 4 },
  slotChip: { paddingHorizontal: 10, paddingVertical: 6, borderRadius: 8, borderWidth: 1.5, borderColor: 'rgba(21,34,56,0.08)', backgroundColor: '#fff' },
  slotChipActive: { borderColor: '#4A8FE8', backgroundColor: 'rgba(74,143,232,0.1)' },
  slotChipText: { fontSize: 13, color: '#4A6080', fontWeight: '600' },
  slotChipTextActive: { color: '#4A8FE8' },
  slotChipDisabled: { borderColor: 'rgba(21,34,56,0.06)', backgroundColor: '#F4F8FF', opacity: 0.5 },
  slotChipTextDisabled: { color: '#7A90AE' },
  fieldError: { fontSize: 13, color: '#EF4444', fontWeight: '600', marginTop: 10 },
  recurToggleRow: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 14, marginBottom: 4 },
  recurBox: { backgroundColor: '#fff', borderRadius: 8, borderWidth: 1, borderColor: 'rgba(21,34,56,0.08)', padding: 12, marginBottom: 4 },
  recurPreview: { fontSize: 13, color: '#4A6080', marginTop: 10, lineHeight: 18 },
  recurConflictBox: { backgroundColor: '#FEF2F2', borderRadius: 10, borderWidth: 1, borderColor: '#FECACA', padding: 14, marginBottom: 16 },
  recurConflictTitle: { fontSize: 13, fontWeight: '700', color: '#B91C1C', marginBottom: 8 },
  recurConflictItem: { fontSize: 13, color: '#7F1D1D', lineHeight: 19 },
  recurSuccessBox: { backgroundColor: '#ECFDF5', borderRadius: 10, borderWidth: 1, borderColor: '#A7F3D0', padding: 14, marginBottom: 16 },
  recurSuccessText: { fontSize: 14, fontWeight: '600', color: '#047857' },
  apptSection: { fontSize: 12, fontWeight: '700', color: '#7A90AE', textTransform: 'uppercase', letterSpacing: 0.5, marginBottom: 8 },
  emptyAppt: { textAlign: 'center', color: '#7A90AE', fontSize: 14, paddingVertical: 20 },
  apptRow: { flexDirection: 'row', alignItems: 'center', gap: 12, paddingVertical: 10, borderBottomWidth: 1, borderBottomColor: '#EEF3FB' },
  apptColorBar: { width: 3, height: 36, borderRadius: 2 },
  apptInfo: { flex: 1 },
  apptProg: { fontSize: 14, fontWeight: '700' },
  apptDate: { fontSize: 12, color: '#4A6080', marginTop: 2 },
  cancelledBadge: { backgroundColor: 'rgba(239,68,68,0.1)', borderRadius: 6, paddingHorizontal: 8, paddingVertical: 3 },
  cancelledText: { fontSize: 11, fontWeight: '700', color: '#EF4444' },
  stornBtn: { backgroundColor: 'rgba(239,68,68,0.1)', borderRadius: 8, paddingHorizontal: 10, paddingVertical: 6 },
  stornText: { fontSize: 12, fontWeight: '700', color: '#EF4444' },
  stornConfirmBox: { backgroundColor: '#FEF2F2', borderWidth: 1, borderColor: '#FECACA', borderRadius: 12, padding: 14, marginTop: 8, marginBottom: 4 },
  stornReasonInput: { minHeight: 52, textAlignVertical: 'top', marginBottom: 10 } as any,
  stornConfirmBtns: { flexDirection: 'row', gap: 10 },
  stornConfirmYes: { flex: 1, backgroundColor: '#EF4444', borderRadius: 10, paddingVertical: 11, alignItems: 'center' },
  stornConfirmYesText: { fontSize: 13, fontWeight: '700', color: '#fff' },
  stornConfirmNo: { backgroundColor: 'rgba(21,34,56,0.06)', borderRadius: 10, paddingVertical: 11, paddingHorizontal: 18, alignItems: 'center' },
  stornConfirmNoText: { fontSize: 13, fontWeight: '600', color: '#4A6080' },
  deleteHeaderBtn: { backgroundColor: 'rgba(239,68,68,0.1)', borderRadius: 8, paddingHorizontal: 14, paddingVertical: 8 },
  deleteHeaderBtnText: { fontSize: 13, fontWeight: '700', color: '#EF4444' },
  deleteConfirmBox: { backgroundColor: '#FEF2F2', borderWidth: 1.5, borderColor: '#FECACA', borderRadius: 14, padding: 20, marginBottom: 16 },
  deleteConfirmTitle: { fontSize: 16, fontWeight: '800', color: '#991B1B', marginBottom: 8 },
  deleteConfirmSub: { fontSize: 14, color: '#7F1D1D', lineHeight: 20, marginBottom: 16 },
  deleteError: { fontSize: 13, color: '#DC2626', fontWeight: '600', marginBottom: 12 },
  deleteConfirmBtns: { flexDirection: 'row', gap: 10 },
  deleteConfirmYes: { flex: 1, backgroundColor: '#EF4444', borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  deleteConfirmYesText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  deleteConfirmNo: { flex: 1, backgroundColor: 'rgba(21,34,56,0.06)', borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  deleteConfirmNoText: { fontSize: 14, fontWeight: '600', color: '#4A6080' },
  birthYearWarning: { backgroundColor: '#FEF3C7', borderRadius: 8, paddingHorizontal: 12, paddingVertical: 10, marginBottom: 4 },
  birthYearWarningText: { fontSize: 13, color: '#92400E' },
  billingHead: { flexDirection: 'row', alignItems: 'baseline', gap: 8 },
  billingCount: { fontSize: 30, fontWeight: '800', color: '#152238' },
  billingCountDue: { color: '#EF4444' },
  billingUnit: { fontSize: 14, fontWeight: '600', color: '#4A6080' },
  billingBar: { flexDirection: 'row', gap: 6, marginTop: 12 },
  billingSegment: { flex: 1, height: 10, borderRadius: 5, backgroundColor: 'rgba(21,34,56,0.08)' },
  billingSegmentFilled: { backgroundColor: '#4A8FE8' },
  billingSegmentDue: { backgroundColor: '#EF4444' },
  billingHint: { fontSize: 13, fontWeight: '600', color: '#4A6080', marginTop: 10 },
  billingHintDue: { color: '#EF4444', fontWeight: '800' },
  billingUpcoming: { fontSize: 13, color: '#7A90AE', marginTop: 4 },
  billingSince: { fontSize: 12, color: '#7A90AE', marginTop: 10 },
  billingResetBtn: { alignSelf: 'flex-start', marginTop: 14, backgroundColor: 'rgba(74,143,232,0.1)', borderRadius: 10, paddingHorizontal: 16, paddingVertical: 10 },
  billingResetBtnText: { fontSize: 13, fontWeight: '700', color: '#4A8FE8' },
  billingResetBtnMuted: { backgroundColor: 'rgba(21,34,56,0.05)' },
  billingResetBtnTextMuted: { color: '#9BAFC7' },
  billingConfirmBox: { marginTop: 14, backgroundColor: '#F4F8FF', borderWidth: 1.5, borderColor: '#D6E4F7', borderRadius: 12, padding: 16 },
  billingConfirmText: { fontSize: 13, color: '#152238', lineHeight: 19, marginBottom: 14 },
  billingConfirmBtns: { flexDirection: 'row', gap: 10 },
  billingConfirmYes: { flex: 1, backgroundColor: '#4A8FE8', borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  billingConfirmYesText: { fontSize: 14, fontWeight: '700', color: '#fff' },
  billingConfirmNo: { flex: 1, backgroundColor: 'rgba(21,34,56,0.06)', borderRadius: 10, paddingVertical: 12, alignItems: 'center' },
  billingConfirmNoText: { fontSize: 14, fontWeight: '600', color: '#4A6080' },
});
